#!/bin/bash
# Run ensureStudy for LAN access with FULL HTTPS
# Required for camera/microphone features on mobile/other devices
# All logs are stored in ./logs directory

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"
VENV_PATH="$PROJECT_ROOT/venv"
LOG_DIR="$PROJECT_ROOT/logs"

# Get local IP address
LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "localhost")

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Create logs directory
mkdir -p "$LOG_DIR"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║       ensureStudy LAN Development (HTTPS Mode)             ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo -e "${BLUE}Local IP: $LOCAL_IP${NC}"
echo -e "${BLUE}Logs stored in: $LOG_DIR${NC}"
echo ""

# Kill any stale processes on our ports
echo -e "${YELLOW}Killing stale processes on ports 8000, 8001, 3000...${NC}"
lsof -ti:8000 | xargs kill -9 2>/dev/null || true
lsof -ti:8001 | xargs kill -9 2>/dev/null || true
lsof -ti:3000 | xargs kill -9 2>/dev/null || true
sleep 1

# ============================================================================
# Check/Generate mkcert certificates
# ============================================================================
CERT_FILE="$PROJECT_ROOT/${LOCAL_IP}+2.pem"
KEY_FILE="$PROJECT_ROOT/${LOCAL_IP}+2-key.pem"

if [ ! -f "$CERT_FILE" ] || [ ! -f "$KEY_FILE" ]; then
    echo -e "${YELLOW}Generating mkcert certificates for $LOCAL_IP...${NC}"
    if ! command -v mkcert &> /dev/null; then
        echo -e "${RED}mkcert not found! Install with: brew install mkcert${NC}"
        exit 1
    fi
    mkcert -install
    cd "$PROJECT_ROOT"
    mkcert "$LOCAL_IP" localhost 127.0.0.1
    echo -e "${GREEN}✓ Certificates generated${NC}"
else
    echo -e "${GREEN}✓ Using existing certificates for $LOCAL_IP${NC}"
fi

# Check if venv exists
if [ ! -d "$VENV_PATH" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_PATH"
fi

# Activate venv
if [ -z "$VIRTUAL_ENV" ] || [ "$VIRTUAL_ENV" != "$VENV_PATH" ]; then
    echo -e "${YELLOW}Activating virtual environment...${NC}"
    source "$VENV_PATH/bin/activate"
else
    echo -e "${GREEN}Virtual environment already active${NC}"
fi

# Load environment variables from .env
if [ -f "$PROJECT_ROOT/.env" ]; then
    export $(grep -v '^#' "$PROJECT_ROOT/.env" | xargs)
fi

# Set environment variables
export FLASK_APP=app
export FLASK_DEBUG=1
export JWT_SECRET="${JWT_SECRET:-local-dev-jwt-secret-key-32chars}"
export PYTHONUNBUFFERED=1

# Date for log files
DATE=$(date +%Y-%m-%d)

# ============================================================================
# Start Core API with HTTPS (using stable runner script)
# ============================================================================
echo -e "${GREEN}Starting Core API on https://$LOCAL_IP:8000${NC}"
cd "$PROJECT_ROOT/backend/core-service"
python run_https.py "$CERT_FILE" "$KEY_FILE" 8000 2>&1 | tee -a "$LOG_DIR/core-service_$DATE.log" &
CORE_PID=$!

sleep 3

# ============================================================================
# Start AI Service with HTTPS
# ============================================================================
echo -e "${GREEN}Starting AI Service on https://$LOCAL_IP:8001${NC}"
cd "$PROJECT_ROOT/backend/ai-service"
python -m uvicorn app.main:app --host 0.0.0.0 --port 8001 \
    --ssl-keyfile "$KEY_FILE" --ssl-certfile "$CERT_FILE" \
    --reload 2>&1 | tee -a "$LOG_DIR/ai-service_$DATE.log" &
AI_PID=$!

sleep 3

# ============================================================================
# Start Frontend with HTTPS
# ============================================================================
echo -e "${GREEN}Starting Frontend on https://$LOCAL_IP:3000${NC}"
cd "$PROJECT_ROOT/frontend"
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Configure frontend for HTTPS LAN access
echo -e "${YELLOW}Configuring frontend for HTTPS LAN access...${NC}"
cat > .env.local << EOF
# Environment Variables for Next.js Frontend (LAN Mode - HTTPS)
# Auto-generated by run-lan.sh

# API URLs (HTTPS on LAN IP: $LOCAL_IP)
NEXT_PUBLIC_API_URL=https://$LOCAL_IP:8000
NEXT_PUBLIC_AI_SERVICE_URL=https://$LOCAL_IP:8001

# NextAuth Configuration
NEXTAUTH_URL=https://$LOCAL_IP:3000
NEXTAUTH_SECRET=local-dev-nextauth-secret-key-32-characters
EOF

echo -e "${GREEN}  → .env.local configured with HTTPS${NC}"

# Start Next.js with experimental HTTPS
NEXTAUTH_SECRET="${JWT_SECRET:-local-dev-jwt-secret-key-32chars}" \
NEXTAUTH_URL="https://$LOCAL_IP:3000" \
npm run dev -- -H 0.0.0.0 --experimental-https 2>&1 | tee -a "$LOG_DIR/frontend_$DATE.log" &
FRONTEND_PID=$!

sleep 5

# ============================================================================
# Display Summary
# ============================================================================
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       ensureStudy LAN (HTTPS) Ready! 🔒                    ║${NC}"
echo -e "${GREEN}╠════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║  Your Network IP: ${BLUE}$LOCAL_IP${GREEN}                               ║${NC}"
echo -e "${GREEN}╠════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║  ${NC}Frontend:       ${BLUE}https://$LOCAL_IP:3000${NC}                   ${GREEN}║${NC}"
echo -e "${GREEN}║  ${NC}Core API:       ${BLUE}https://$LOCAL_IP:8000${NC}                   ${GREEN}║${NC}"
echo -e "${GREEN}║  ${NC}AI Service:     ${BLUE}https://$LOCAL_IP:8001${NC}                   ${GREEN}║${NC}"
echo -e "${GREEN}║  ${NC}AI Docs:        ${BLUE}https://$LOCAL_IP:8001/docs${NC}              ${GREEN}║${NC}"
echo -e "${GREEN}╠════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║  ${YELLOW}⚠️  FOR OTHER DEVICES - Accept certs first:${NC}               ${GREEN}║${NC}"
echo -e "${GREEN}║  ${NC}1. Visit ${BLUE}https://$LOCAL_IP:8000${NC} → Accept cert           ${GREEN}║${NC}"
echo -e "${GREEN}║  ${NC}2. Visit ${BLUE}https://$LOCAL_IP:8001${NC} → Accept cert           ${GREEN}║${NC}"
echo -e "${GREEN}║  ${NC}3. Then use ${BLUE}https://$LOCAL_IP:3000${NC}                      ${GREEN}║${NC}"
echo -e "${GREEN}╠════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║  ${NC}Logs: ${YELLOW}$LOG_DIR${NC}                          ${GREEN}║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Camera/Microphone: ✅ Enabled (HTTPS mode)${NC}"
echo ""
echo "Press Ctrl+C to stop all services"

# Trap Ctrl+C and cleanup
cleanup() {
    echo ""
    echo -e "${YELLOW}Stopping services...${NC}"
    kill $CORE_PID $AI_PID $FRONTEND_PID 2>/dev/null
    echo -e "${GREEN}All services stopped. Logs saved to $LOG_DIR${NC}"
    exit 0
}

trap cleanup SIGINT SIGTERM

# Wait for any process to exit
wait
