"""
Descriptive Interview Questions Model

Stores AI-generated questions with expected answers for mock interviews.
Each topic can have multiple questions (N questions per topic).
"""
from datetime import datetime
from app import db
import uuid


def generate_uuid():
    return str(uuid.uuid4())


class DescriptiveQuestion(db.Model):
    """
    AI-generated descriptive question for mock interviews.
    
    Each question belongs to a ClassroomTopic and includes:
    - Question text
    - Expected answer (reference)
    - Key concepts that should be covered
    - Difficulty level
    - Usage statistics
    """
    __tablename__ = 'descriptive_questions'
    
    id = db.Column(db.String(36), primary_key=True, default=generate_uuid)
    
    # Link to ClassroomTopic
    topic_id = db.Column(db.String(36), db.ForeignKey('classroom_topics.id'), nullable=False, index=True)
    
    # Question content
    question_text = db.Column(db.Text, nullable=False)
    expected_answer = db.Column(db.Text, nullable=False)
    
    # Key concepts that should be mentioned in the answer
    # E.g., ["Newton's Laws", "Force", "Mass", "Acceleration"]
    key_concepts = db.Column(db.JSON, default=list)
    
    # Difficulty: easy, medium, hard
    difficulty = db.Column(db.String(20), default='medium')
    
    # Usage statistics
    times_asked = db.Column(db.Integer, default=0)
    times_correct = db.Column(db.Integer, default=0)  # Score >= 70%
    avg_score = db.Column(db.Float, default=0.0)
    
    # Metadata
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    is_active = db.Column(db.Boolean, default=True)
    
    # Generated by (AI model or manual)
    source = db.Column(db.String(50), default='ai_generated')
    
    def to_dict(self):
        return {
            'id': self.id,
            'topic_id': self.topic_id,
            'question_text': self.question_text,
            'expected_answer': self.expected_answer,
            'key_concepts': self.key_concepts or [],
            'difficulty': self.difficulty,
            'times_asked': self.times_asked,
            'avg_score': round(self.avg_score, 1) if self.avg_score else 0,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'is_active': self.is_active
        }
    
    def to_interview_dict(self):
        """Format for interview session (without expected answer for student view)"""
        return {
            'id': self.id,
            'question': self.question_text,
            'topic_id': self.topic_id,
            'difficulty': self.difficulty
        }
    
    def to_evaluation_dict(self):
        """Format for answer evaluation (includes expected answer)"""
        return {
            'id': self.id,
            'question': self.question_text,
            'reference_answer': self.expected_answer,
            'key_concepts': self.key_concepts or []
        }
    
    def update_stats(self, score: float):
        """Update usage statistics after an answer is evaluated"""
        self.times_asked += 1
        if score >= 70:
            self.times_correct += 1
        # Running average
        if self.avg_score == 0:
            self.avg_score = score
        else:
            self.avg_score = (self.avg_score * (self.times_asked - 1) + score) / self.times_asked
    
    def __repr__(self):
        return f"<DescriptiveQuestion {self.id[:8]}... '{self.question_text[:30]}...'>"


class StudentQuestionAttempt(db.Model):
    """
    Tracks individual student attempts at answering questions.
    Used for:
    - Preventing repeat questions in same session
    - Historical performance analysis
    - Identifying which questions to regenerate
    """
    __tablename__ = 'student_question_attempts'
    
    id = db.Column(db.String(36), primary_key=True, default=generate_uuid)
    
    user_id = db.Column(db.String(36), db.ForeignKey('users.id'), nullable=False, index=True)
    question_id = db.Column(db.String(36), db.ForeignKey('descriptive_questions.id'), nullable=False, index=True)
    session_id = db.Column(db.String(36), index=True)  # Mock interview session
    
    # Student's answer (transcribed from speech)
    student_answer = db.Column(db.Text)
    
    # Evaluation results
    score = db.Column(db.Float, default=0.0)
    concept_scores = db.Column(db.JSON)  # {concept: score}
    feedback = db.Column(db.Text)
    
    # Time tracking
    response_time_seconds = db.Column(db.Integer)  # How long student took to answer
    audio_duration_seconds = db.Column(db.Float)  # Length of audio response
    
    attempted_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # Relationship
    question = db.relationship('DescriptiveQuestion', backref='attempts')
    
    def to_dict(self):
        return {
            'id': self.id,
            'question_id': self.question_id,
            'score': round(self.score, 1) if self.score else 0,
            'concept_scores': self.concept_scores or {},
            'feedback': self.feedback,
            'attempted_at': self.attempted_at.isoformat() if self.attempted_at else None
        }
